
openapi: 3.0.0  # Add OpenAPI version here
info:
  title: WebSocket API
  description: WebSocket API documentation for the ACC drawing game "Scribblers"
  version: 1.0.0

paths:
  /socket.io:
    post:
      summary: WebSocket Connection
      description: Establishes a WebSocket connection using Socket.io
      responses:
        101:
          description: Switching Protocols - Connection established

# Defines the schemas (data structures) for the events in the WebSocket API
components:
  schemas:
    DrawEvent:
      type: object
      description: Data structure for sending drawing information
      properties:
        x:
          type: number
          description: The x-coordinate of the drawing stroke
        y:
          type: number
          description: The y-coordinate of the drawing stroke
        color:
          type: string
          description: The color of the stroke
        thickness:
          type: number
          description: The thickness of the stroke
        strokeId: 
          type: number
          description: The ID of the stroke

    EraseEvent:
      type: object
      description: Data structure for sending erasing information
      properties:
        x:
          type: number
          description: The x-coordinate of the erasing stroke
        y:
          type: number
          description: The y-coordinate of the erasing stroke
        thickness:
          type: number
          description: The thickness of the stroke
        strokeId: 
          type: number
          description: The ID of the stroke

    UndoEvent:
      type: object
      description: Data structure for sending drawing-undo information
      properties:
        strokeId: 
          type: number
          description: The ID of the stroke to be undone

    GuessEvent:
      type: object
      description: Data structure for a player's word guess
      properties:
        playerId:
          type: number
          description: The unique ID of the player making the guess
        word:
          type: string
          description: The word the player is guessing 

    AACSelectSymbolEvent:
      type: object
      description: Event data for when a player selects a symbol from the AAC guess interface
      properties:
        playerId:
          type: number
          description: The unique ID of the player selecting the symbol
        symbolId:
          type: number
          description: The unique ID of the selected symbol
        text:
          type: string
          description: The text representation of the selected symbol

    AACDeleteSymbolEvent:
      type: object
      description: Event data for when a player deletes a symbol from the AAC guess interface
      properties:
        playerId:
          type: number
          description: The unique ID of the player selecting the symbol
        symbolId:
          type: number
          description: The unique ID of the selected symbol

    AACSendMessageEvent:
      type: object
      description: Event data for when a player sends a message using the AAC board
      properties:
        playerId:
          type: number
          description: The unique ID of the player sending the message
        message:
          type: string
          description: The message composed using the AAC board

  # Custom WebSocket message definitions, mimicking REST API calls
  messages:
    draw:
      description: WebSocket event for sending drawing data
      payload:
        $ref: "#/components/schemas/DrawEvent"

    erase:
      description: WebSocket event for erasing drawing data
      payload:
        $ref: "#/components/schemas/EraseEvent"

    undo:
      description: WebSocket event for undoing drawing data
      payload:
        $ref: "#/components/schemas/UndoEvent"

    guess:
      description: WebSocket event for submitting a player's guess
      payload:
        $ref: "#/components/schemas/GuessEvent"

    aac_select_symbol:
      description: WebSocket event for selecting a symbol on the AAC board
      payload:
        $ref: "#/components/schemas/AACSelectSymbolEvent"

    aac_delete_symbol:
      descriptio: WebSocket event for deleting a selected symbol on the AAC board
      payload:
        $ref: "#/components/schemas/AACDeletSymbolEvent"

    aac_send_message:
      description: WebSocket event for sending a message using the AAC board
      payload:
        $ref: "#/components/schemas/AACSendMessageEvent"
