apiVersion: v1
kind: Service
metadata:
  name: node-backend-service
  namespace: aac-game
spec:
  selector:
    app: node-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer
